// <auto-generated />
using IDPA_Hauptprojekt_2024.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IDPA_Hauptprojekt_2024.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("IDPA_Hauptprojekt_2024.Database.Model.ArticleKeyword", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeywordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArticleId", "KeywordId");

                    b.HasIndex("KeywordId");

                    b.ToTable("ArticleKeywords");
                });

            modelBuilder.Entity("IDPA_Hauptprojekt_2024.Database.Model.Articles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleNr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char?>("Letter")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Paragraph")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Subsection")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("IDPA_Hauptprojekt_2024.Database.Model.Keywords", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("IDPA_Hauptprojekt_2024.Database.Model.ArticleKeyword", b =>
                {
                    b.HasOne("IDPA_Hauptprojekt_2024.Database.Model.Articles", "Article")
                        .WithMany("ArticleKeywords")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDPA_Hauptprojekt_2024.Database.Model.Keywords", "Keyword")
                        .WithMany("ArticleKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("IDPA_Hauptprojekt_2024.Database.Model.Articles", b =>
                {
                    b.Navigation("ArticleKeywords");
                });

            modelBuilder.Entity("IDPA_Hauptprojekt_2024.Database.Model.Keywords", b =>
                {
                    b.Navigation("ArticleKeywords");
                });
#pragma warning restore 612, 618
        }
    }
}
